# Generated by Django 5.2.1 on 2025-05-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakila', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('actors', models.ManyToManyField(related_name='films', to='sakila.actor')),
            ],
        ),
    ]
