# Generated by Django 5.2.1 on 2025-05-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sakila', '0003_actor_film'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelTable(
            name='film',
            table='film',
        ),
    ]
