# Generated by Django 5.2.1 on 2025-05-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sakila', '0004_alter_film_options_alter_film_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'managed': False},
        ),
    ]
