# Generated by Django 5.2.1 on 2025-05-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sakila', '0005_alter_film_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'managed': False},
        ),
    ]
