# Generated by Django 5.2.1 on 2025-05-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakila', '0006_alter_actor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'film_actor',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='actor',
            table='actor',
        ),
    ]
