# Generated by Django 5.2.1 on 2025-05-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakila', '0007_filmactor_alter_actor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'managed': False, 'ordering': ['city']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'managed': False, 'ordering': ['country']},
        ),
    ]
